spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${CALENDAR_PGHOST}
    username: ${CALENDAR_PGUSER}
    password: ${CALENDAR_PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: my-redis
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 5000ms
        shutdown-timeout: 200ms
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false
      key-prefix: calendars-service
      use-key-prefix: true
      enable-statistics: true
      
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: init
    baseline-version: 0
    url: ${CALENDAR_PGHOST}
    user: ${CALENDAR_PGUSER}
    password: ${CALENDAR_PGPASSWORD}

google:
  calendar:
    enabled: true
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    application-name: Calendar Sync App
    calendar-id: primary

zoom:
  api:
    account-id: ${ZOOM_ACCOUNT_ID}
    client-id: ${ZOOM_CLIENT_ID}
    client-secret: ${ZOOM_CLIENT_SECRET}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET_NAME}

server:
  port: ${PORT:8082}