eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: false
    instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${server.port}/eureka/

server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server